;; -*- lexical-binding: t -*-

(ert-deftest rustic-test-window-count ()
  (should (= (length (window-list)) 1))
  (let* ((dir (rustic-babel-generate-project t)))
    (setq compilation-arguments "cargo fmt")
    (let* ((default-directory dir)
           (compilation-read-command nil)
           (proc (rustic-compile)))
      (rustic-test--wait-till-finished rustic-compilation-buffer-name)
      (should (= (length (window-list)) 2))
      (should (get-buffer-window rustic-compilation-buffer-name)))))

(ert-deftest rustic-test-window-count-format-proc ()
  (should (= (length (window-list)) 1))
  (let ((string "ffn main()      {}")
        (formatted-string "fn main() {}\n")
        (buf (get-buffer-create "test"))
        (buffer-read-only nil))
    (with-current-buffer buf
      (erase-buffer)
      (rustic-mode)
      (insert string)
      (let ((proc (rustic-format-buffer)))
        (rustic-test--wait-till-finished rustic-compilation-buffer-name))
      (should (= (length (window-list)) 2))
      (should (get-buffer-window rustic-format-buffer-name)))
    (kill-buffer buf)))
